APPfoto/urls.py
from django.urls import path
from . import views

app_name = "APPfoto"

urlpatterns = [
    path(" /", views.home_view, name="home"),
    path("ricerca", views.search, name="cercaFoto"),
    path("ricerca/<str:sstring>/<str:where>", views.FotoListaRicercataView.as_view(), name="ricerca_risultati"),
    path("crea_foto/", views.CreateFotoView.as_view(), name="creafoto"),
    path("lista_foto/", views.FotoListView.as_view(), name="listafoto"),
    path("situation/", views.my_situation, name="situation"),
    path("acquisto/<int:foto_id>/", views.CreaAcquisto, name="acquisto"),
    path("fotografi_lista", views.FotografiListView.as_view(), name="listafotografi"),
    path('CreaRecensione/<int:acquisto_id>/', views.CreaRecensione, name='CreaRecensione'),
    path('recensioni_utente/', views.RecensioniUtente, name='RecensioniUtente'),
    path('for_you_page', views.forYouView, name="foryoupage")

]

foto_commerce/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.contrib.auth import views as auth_views
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('APPfoto/', include('APPfoto.urls')),
    re_path(r"^$|^\/$|^home\/$",home,name="home"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("registrafotografo", FotografoCreateView.as_view(), name="registrafotografo")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foto_commerce/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group


class CreaUtenteCliente(UserCreationForm):
    def save(self, commit=True):
        user = super().save(commit)
        g = Group.objects.get(name="Clienti")
        g.user_set.add(user)
        return user


class CreaUtenteFotografo(UserCreationForm):

    def save(self, commit=True):
        user = super().save(commit)
        g = Group.objects.get(name="Fotografi")
        g.user_set.add(user)
        return user

foto_commerce/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from APPfoto.models import Foto
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import PermissionRequiredMixin

def home(request):
    recent_photos = Foto.objects.order_by('-creation_date')[:5]  # 5 FOTO PIÙ NUOVE NEL CAROSELLO
    context = {'recent_photos': recent_photos}
    return render(request, 'home.html', context)


class UserCreateView(CreateView):
    form_class = CreaUtenteCliente
    template_name = "user_create.html"
    success_url = reverse_lazy("login")


class FotografoCreateView(PermissionRequiredMixin, UserCreateView):
    permission_required = "is_staff"
    form_class = CreaUtenteFotografo

foto_commerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <style>
  .header-background {
    background-image: url('/static/space2.jpg');
    background-size: cover;
    background-position: top;
    background-repeat: no-repeat;
    color: white;
  }
</style>

  {% endblock %}
  {% load crispy_forms_tags %}

</head>


<title>{% block title %} {% endblock %}</title>

<body>

<div class="jumbotron text-center header-background" style="margin-bottom:0">
  {% block header1 %}
    <h1>Header</h1>
    <p>Subtitle</p>
  {% endblock %}
</div>


{% if user.is_authenticated and "ok" in request.GET.login  %}

<div id="info" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"> Login di {{user.username}} !</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> Login avvenuto con successo, funzioni utente registrato ora disponibili</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Chiudi</button>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
      $("#info").modal('show');
  });
</script>

{% endif %}


<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    {% block navbar %}
    <a class="navbar-brand" href="{% url 'home' %}">Foto Gallery</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">


        <li class="nav-item">
          <a class="nav-link" href="{% url 'APPfoto:home' %}">Gestione Utente</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'APPfoto:listafoto' %}">Vetrina Foto</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'APPfoto:cercaFoto' %}"> Cerca Una Foto Nel Sito</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href={% url 'APPfoto:listafotografi' %}> I Nostri Fotografi</a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href={% url 'APPfoto:foryoupage' %}> Scelti per Te </a>
        </li>
      </ul>
    </div>
    {% endblock %}
  </nav>



  <div class="container" style="margin-top:30px">

      <div class="col-sm-22">
        <center>

        {% block content %}
        <h2>QUI TITOLO ACCATTIVANTE</h2>
        <h5>Sottotitolo meno accattivante ma pur sempre rilevante</h5>
        <div class="fakeimg">Fake Image</div>
        <p>Did you ever hear the tragedy of Darth Plagueis the wise?</p>
        <p>I thought not, it's not a story the jedi would tell you </p>
        {% endblock %}
        <br>
        </center>
      </div>
    </div>


  <div class="jumbotron text-center" style="margin-bottom:0">
    {% block footer %}

      {% if user.is_authenticated %}
      <a class="btn btn-info" href="{% url 'logout' %}" role="button">Logout</a>
      {% else %}
      <a class="btn btn-info" href="{% url 'register' %}" role="button">Sei nuovo? Registrati</a>
      <a class="btn btn-info" href="{% url 'login' %}" role="button">Login</a>
      {% endif %}

      <a class="btn btn-warning" href="/admin/" role="button">Login Admin</a>

    {%  endblock %}
  </div>


  </body>
  </html>

foto_commerce/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Foto Gallery {% endblock %}

{% block header1 %}
  <h1>Foto Gallery</h1>
  <p>Welcome to the Foto Gallery
    <br>
    Siediti e gustati lo spettacolo</p>
{% endblock %}

{% block content %}
<h2>Home di Foto Gallery</h2>
<h5>Ecco le ultime novità: </h5>

<div id="recent-photos-carousel" class="carousel slide" data-ride="carousel" data-interval="3000">
  <!-- INDICATORI -->
  <ol class="carousel-indicators">
    {% for foto in recent_photos %}
    <li data-target="#recent-photos-carousel" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
    {% endfor %}
  </ol>

  <!-- FOTO CHE SCORRONO -->
  <div class="carousel-inner">
    {% for foto in recent_photos %}
    <br>
    <div class="carousel-item {% if forloop.first %}active{% endif %}">
      <a href="{% url 'APPfoto:ricerca_risultati' foto.name 'name' %}">
        <h2>{{ foto.name }}</h2>
        <br>
        <img src="{{ foto.actual_photo.url }}" alt="{{ foto.name }}" style="max-width: 400px; max-height: 400px;">
      </a>
      <br>
      <br>
      <br>
    </div>
    {% endfor %}
  </div>

  <!-- QUI CI SONO I CONTROLLI DELLA GIOSTRA -->
  <a class="carousel-control-prev" href="#recent-photos-carousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#recent-photos-carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endblock %}

foto_commerce/templates/user_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block title %} Creazione Utente {{ form.user_group_name }} {% endblock %}

{% block header1 %}
  <h1>Registrati ora!</h1>
  <p>Compilare tutti i campi</p>
{% endblock %}

{% block content %}

<form method="post"> {% csrf_token %}

  {{form | crispy}}

  <input type="submit" class="btn btn-success" value="Conferma e Registrati">

  </form>

{% endblock %}

{% block footer %} {% endblock %}