APPfoto/urls.py
from django.urls import path
from . import views

app_name = "APPfoto"

urlpatterns = [
    path(" /", views.home_view, name="home"),
    path("ricerca", views.search, name="cercaFoto"),
    path("ricerca/<str:sstring>/<str:where>", views.FotoListaRicercataView.as_view(), name="ricerca_risultati"),
    path("crea_foto/", views.CreateFotoView.as_view(), name="creafoto"),
    path("lista_foto/", views.FotoListView.as_view(), name="listafoto"),
    path("situation/", views.my_situation, name="situation"),
    path("acquisto/<int:foto_id>/", views.CreaAcquisto, name="acquisto"),
    path("fotografi_lista", views.FotografiListView.as_view(), name="listafotografi"),
    path('CreaRecensione/<int:acquisto_id>/', views.CreaRecensione, name='CreaRecensione'),
    path('recensioni_utente/', views.RecensioniUtente, name='RecensioniUtente'),
    path('for_you_page', views.forYouView, name="foryoupage")

]

foto_commerce/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.contrib.auth import views as auth_views
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('APPfoto/', include('APPfoto.urls')),
    re_path(r"^$|^\/$|^home\/$",home,name="home"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("registrafotografo", FotografoCreateView.as_view(), name="registrafotografo")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

APPfoto/models.py
from django.db import models
from django.contrib.auth.models import User

class Foto(models.Model):
    COLOUR_CHOICES = [
        ("Black", "Black"),
        ("Dark Blue", "Dark Blue"),
        ("Green", "Green"),
        ("Grey", "Grey"),
        ("Light Blue", "Light Blue"),
        ("Orange", "Orange"),
        ("Pink", "Pink"),
        ("Purple", "Purple"),
        ("Red", "Red"),
        ("White", "White"),
        ("Yellow", "Yellow"),
    ]

    name = models.CharField(max_length=50, default="No name Given")
    main_colour = models.CharField(max_length=100, choices=COLOUR_CHOICES)
    landscape = models.BooleanField()
    actual_photo = models.ImageField(upload_to='uploads/')
    artist = models.ForeignKey(User, on_delete=models.CASCADE, default=0, related_name="foto")
    price = models.DecimalField(verbose_name="prezzo", max_digits=5, decimal_places=2, default=0.00)
    creation_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        if self.landscape:
            return f"{self.name}, landscape a partire da: " + str(self.price)
        else:
            return f"{self.name}, portrait a partire da: " + str(self.price)





class Acquisto(models.Model):

    MATERIALE_DI_STAMPA = [
        ("0.00", "Carta Standard (+0.00)"),
        ("1.00", "Tela (+1.00)"),
        ("2.00", "Carta Fotografica (+2.00)"),
        ("3.50", "Puzzle (+3.50)"),
        ("3.00", "Lamiera Semplice (+3.00)"),
        ("4.00", "Lamiera Premium (+4.00)")
    ]

    DIMENSIONI = [
        ("0.00", "10 x 15   (+0.00)"),
        ("2.00", "12 x 18   (+2.00)"),
        ("3.00", "13 x 19   (+3.00)")
    ]

    foto = models.ForeignKey(Foto, on_delete=models.CASCADE, related_name="venduti")
    acquirente = models.ForeignKey(User, on_delete=models.CASCADE, related_name="acquisti")
    materiale = models.CharField(max_length=100, choices=MATERIALE_DI_STAMPA)
    dimensioni = models.CharField(max_length=100, choices=DIMENSIONI)
    prezzo = models.DecimalField(verbose_name="prezzo", max_digits=6, decimal_places=2, blank=True, null=True)


class Recensione(models.Model):
    foto = models.ForeignKey(Foto, on_delete=models.CASCADE, related_name="recensioni")
    utente = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recensioni_scritte")
    testo = models.CharField(max_length=250, default="Questo utente non ha lasciato una recensione scritta, "
                                                     "solo un voto.")
    voto = models.PositiveIntegerField()
    fotografo = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recensioni", null=True, blank=True)
    acquisto=models.ForeignKey(Acquisto, on_delete=models.CASCADE, related_name="recensioni", null=True, blank=True)

    def scritta_da(self):
        return self.utente.username

    def testo_della_recensione(self):
        return self.testo

    def valutata(self):
       return "Valutata " + str(self.voto) + " su 10"

    def save(self, *args, **kwargs):
        if self.foto:
            self.fotografo = self.foto.artist
        super(Recensione, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Recensioni"

APPfoto/views.py
from django.db.models.functions import Coalesce
from django.shortcuts import redirect, get_object_or_404
from .forms import *
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from decimal import Decimal, ROUND_UP
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import SearchForm
from django.shortcuts import render
from django.db.models import Avg, Count, Subquery, OuterRef, Value



def home_view(request):
    return render(request, template_name="APPfotoTempl/home.html")


def forYouView(request):
    user = request.user

    # PRIMO PASSO: fotografo preferito dall'utente
    if user.is_authenticated:
        fotografo_prefe = Recensione.objects.filter(
            acquisto__acquirente=user
        ).values('acquisto__foto__artist').annotate(
            avg_rating=Avg('voto')
        ).order_by('-avg_rating').first()
    else:
        fotografo_prefe = None

    # SECONDO PASSO, le foto del fotografo prefe o del miglior fotografo complessivamente
    if fotografo_prefe:
        preferenze = Foto.objects.filter(artist=fotografo_prefe['acquisto__foto__artist'])[:7]
    else:
        best_photographer = Recensione.objects.values('acquisto__foto__artist').annotate(
            avg_rating=Avg('voto')
        ).order_by('-avg_rating').first()

        if best_photographer:
            preferenze = Foto.objects.filter(artist=best_photographer['acquisto__foto__artist'])[:7]
        else:
            preferenze = []

    foto_recenti = Foto.objects.order_by('-creation_date')[:7]

    best_selling_foto = Foto.objects.annotate(
        acquisto_count=Count('venduti')
    ).order_by('-acquisto_count')[:7]

    context = {
        'foto_recenti': foto_recenti,
        'best_selling_foto': best_selling_foto,
        'le_tue_preferenze': preferenze,
    }

    return render(request, 'APPfotoTempl/for_you_page.html', context)

class FotografiListView(ListView):
    template_name = 'APPfotoTempl/lista_fotografi.html'
    context_object_name = 'members'

    def get_queryset(self):
        fotografi_group = Group.objects.get(name='Fotografi')

        subquery = Acquisto.objects.filter(foto__artist=OuterRef('pk')).values('foto__artist').annotate(
            venduti_count=Count('id')
        ).values('venduti_count')

        members = User.objects.filter(groups=fotografi_group).annotate(
            average_review=Avg('recensioni__voto'),
            foto_count=Count('foto', distinct=True),  # Count distinct photos
            venduti_count=Subquery(subquery[:1])
        )

        sort_by = self.request.GET.get('sort')
        if sort_by == 'positive_reviews':
            members = members.order_by('-average_review')
        elif sort_by == 'alphabetical':
            members = members.order_by('username')
        elif sort_by == 'best_seller':
            members = members.order_by('-venduti_count')

        return members



class FotoListView(ListView):
    titolo = "Abbiamo trovato queste foto"
    model = Foto
    template_name = "APPfotoTempl/lista_foto.html"


    def get_queryset(self):
        queryset = super().get_queryset()
        sort = self.request.GET.get('sort', None)

        queryset = queryset.annotate(
            acquisto_count=Coalesce(Count('venduti'), Value(0, output_field=models.IntegerField())))

        queryset = queryset.order_by('-creation_date')

        if sort == 'price':
            queryset = queryset.order_by('price')
        elif sort == 'new':
            queryset = queryset.order_by('-creation_date')
        elif sort == 'best seller':
            queryset = queryset.order_by('-acquisto_count')

        return queryset


class FotoListaRicercataView(FotoListView):
    model = Foto
    template_name = "APPfotoTempl/lista_foto.html"
    titolo = 'risultati ricerca'

    def get_queryset(self):
        where = self.kwargs['where']
        sstring = self.kwargs['sstring']

        queryset = Foto.objects.all()

        queryset = queryset.annotate(
            acquisto_count=Coalesce(Count('venduti'), Value(0, output_field=models.IntegerField())))

        if where == "name":
            queryset = queryset.filter(name__icontains=sstring)
        elif where == "landscape":
            if sstring == "True":
                queryset = queryset.filter(landscape=True)
            else:
                queryset = queryset.filter(landscape=False)
        elif where == "main_colour":
            queryset = queryset.filter(main_colour__icontains=sstring)
        elif where == "artist":

            queryset = queryset.filter(artist__id=sstring)

        return queryset


def search(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            search_where = form.cleaned_data['search_where']
            if search_where == "name":
                sstring = form.cleaned_data['search_string']
            elif search_where == "landscape":
                sstring = form.cleaned_data['landscape']
            elif search_where == "main_colour":
                sstring = form.cleaned_data['main_colour']
            elif search_where == "artist":
                sstring = form.cleaned_data['artist']
            else:
                messages.error(request, "Invalid form data. Please correct the errors.")


            if not sstring:
                sstring = "SEARCH SOMETHING, ANYTHING"

            return redirect("APPfoto:ricerca_risultati", sstring=sstring, where=search_where)
    else:
        form = SearchForm()


    return render(request, 'APPfotoTempl/search.html', {'form': form})


class CreateFotoView(LoginRequiredMixin, CreateView):
    model = Foto
    fields = ['name', 'main_colour', 'price', 'landscape', 'actual_photo']
    template_name = 'APPfotoTempl/create_entry.html'
    success_url = reverse_lazy("APPfoto:home")

    def form_valid(self, form):
       # stesso nome, brutte cose
        existing_foto = Foto.objects.filter(name=form.cleaned_data['name']).first()
        existing__actual_photo = Foto.objects.filter(actual_photo=form.cleaned_data['actual_photo']).first

        if existing_foto or existing__actual_photo:
            # stesso nome, brutte cose
            messages.error(self.request, 'A Foto with this name or Filename (actual_photo) already exists.')
            return render(self.request, self.template_name, {'form': form})

        form.instance.artist = self.request.user

        return super().form_valid(form)

@login_required
def my_situation(request):
     user = get_object_or_404(User, pk=request.user.pk)
     return render(request, "APPfotoTempl/situation.html")


@login_required
def CreaAcquisto(request, foto_id):
    foto = Foto.objects.get(pk=foto_id)
    artist = foto.artist

    # LISTONE DELLE FOTO DI STO TIZIO MA TOLGO LA FOTO CORRENTR
    artist_photos = Foto.objects.filter(artist=artist).exclude(pk=foto_id)

    if request.method == "POST":
        form = AcquistoForm(request.POST, initial={'foto': foto, 'acquirente': request.user})

        if form.is_valid():
            acquisto = form.save(commit=False)
            acquisto.foto = foto
            acquisto.acquirente = request.user

            materiale_value = float(form.cleaned_data['materiale'])
            dimensioni_value = float(form.cleaned_data['dimensioni'])

            foto_price = float(foto.price)

            prezzo = Decimal(foto_price) + Decimal(materiale_value) + Decimal(dimensioni_value)
            prezzo = prezzo.quantize(Decimal('0.00'), rounding=ROUND_UP)

            acquisto.prezzo = prezzo

            acquisto.save()
            return redirect('APPfoto:situation')
        else:
            messages.error(request, "Invalid form data. Please correct the errors.")
    else:
        initial_data = {'foto': foto, 'acquirente': request.user}
        form = AcquistoForm(initial=initial_data)


    form.fields['acquirente'].widget.attrs['readonly'] = True
    form.fields['acquirente'].widget.attrs['disabled'] = True

    form.fields['materiale'].label = "Materiale"
    form.fields['dimensioni'].label = "Dimensioni"

    context = {
        'foto': foto,
        'form': form,
        'artist_photos': artist_photos
    }

    return render(request, 'APPfotoTempl/acquisto.html', context)


@login_required
def CreaRecensione(request, acquisto_id):
    acquisto = get_object_or_404(Acquisto, pk=acquisto_id)
    existing_recensione = Recensione.objects.filter(acquisto=acquisto, utente=request.user).first()
    foto = get_object_or_404(Foto, pk=acquisto.foto_id)


    if request.method == 'POST':
        form = RecensioneForm(request.POST, initial={'foto': foto, 'acquisto': acquisto, 'utente': request.user,
                                                     'fotografo' : foto.artist})
        if form.is_valid():
            recensione = form.save(commit=False)
            recensione.acquisto = acquisto
            recensione.utente = request.user
            recensione.foto = foto
            recensione.fotografo = foto.artist
            recensione.save()
            return redirect('APPfoto:situation')
        else:
            messages.error(request, "Form non valido, sistemare per favore")
    else:
        initial_data = {'foto': foto, 'acquisto': acquisto, 'utente': request.user,
                   'fotografo': foto.artist}
        form = RecensioneForm(initial=initial_data)

    form.fields['utente'].widget.attrs['readonly'] = True
    form.fields['utente'].widget.attrs['disabled'] = True
    form.fields['foto'].widget.attrs['readonly'] = True
    form.fields['foto'].widget.attrs['disabled'] = True

    context = {
        'acquisto': acquisto_id,
        'foto': acquisto.foto_id,
        'form': form,
        'user_has_recensione': existing_recensione is not None,
    }

APPfoto/templates/APPfotoTempl/acquisto.html
{% extends 'base.html' %}

{% block title %} Acquisto {% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %}
  <h1> Effettua un Acquisto </h1>
{% endblock %}

{% block content %}

<br>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Completa l'acquisto</button>
      </form>
    </div>
  </div>
</div>

<br>
<br>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div id="artist-photos-carousel" class="carousel slide" data-ride="carousel" data-interval="3000">
        <ol class="carousel-indicators">
          {% for foto in artist_photos %}
          <li data-target="#artist-photos-carousel" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
          {% endfor %}
        </ol>
        <br>
        <div class="carousel-inner">
          {% for foto in artist_photos %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <a href="{% url 'APPfoto:ricerca_risultati' foto.name 'name' %}">
              <h2>{{ foto.name }}</h2>
              <br>
              <img src="{{ foto.actual_photo.url }}" alt="{{ foto.name }}" style="max-width: 400px; max-height: 400px;">
            </a>
            <br>
            <br>
            <p>Foto dello stesso artista</p>
            <br>
            <br>
          </div>
          {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#artist-photos-carousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#artist-photos-carousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>



{% endblock %}

APPfoto/templates/APPfotoTempl/create_entry.html
{% extends 'base.html' %}

{% block title %} {{ view.title }} {% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %}
  <h1> {{ view.title }} </h1>
{% endblock %}

{% block content %}

    {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}


<br>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Aggiungi Foto</button>
      </form>
    </div>
  </div>
</div>

<br>

{% endblock %}

APPfoto/templates/APPfotoTempl/home.html
{% extends 'base.html' %}

{% block title %} Home di Foto Gallery {% endblock %}

{% block header1 %}
  <h1>Home di Foto Gallery</h1>
  <p>Welcome
    {% if user.is_authenticated %}
     {{ user.username }}
    {% else %}
    Utente non registrato
    {% endif %}
  </p>
{% endblock %}

{% block content %}

<h2>Cosa si fa di bello?</h2>

<br>

<div class="list-group">
  <a href="{% url 'APPfoto:cercaFoto' %}" class="list-group-item list-group-item-info">Cerca una foto</a>
  <a href="{% url 'APPfoto:listafoto' %}" class="list-group-item list-group-item-info">Elenco delle Foto</a>
  <a href="{% url 'APPfoto:situation' %}" class="list-group-item list-group-item-info">Cronologia Acquisti e Recensioni</a>
</div>

<br>

{% if user.is_staff %}
<br>
<a href="{% url 'registrafotografo' %}" class="list-group-item list-group-item-danger">Iscrivi un fotografo alla gilda</a>
<br>
{% endif %}


{% if "Fotografi" in user.groups.all.0.name or user.is_staff %}
<br>
<a href="{% url 'APPfoto:creafoto' %}" class="list-group-item list-group-item-warning">Aggiungi una foto</a>
<br>
{% endif %}


{% endblock %}

APPfoto/templates/APPfotoTempl/lista_foto.html
{% extends 'base.html' %}

{% block title %} Elenco Foto{% endblock %}

{% load static %}

{% block header1 %}
  <h1>Elenco Foto</h1>
{% endblock %}

{% block content %}
<h2> Vetrina con {{ object_list.count }} Foto </h2>
<br>

<div class="btn-group" role="group">
    <a href="?sort=price" class="btn btn-secondary">Prezzo crescente</a>
    <a href="?sort=new" class="btn btn-secondary">I più nuovi</a>
    <a href="?sort=best seller" class="btn btn-secondary">Best Seller</a>
</div>

<br>
{% if object_list %}
    {% for f in object_list %}
    <br>
    <div class="card">
        <div class="card-header">
        <img src="{{ f.actual_photo.url }}" alt="{{ f.name }}" style="max-width: 400px; max-height: 400px;">
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ f.name }}</h5>
            {% if f.landscape %}
    <p class="card-text">foto scattata da {{ f.artist.username }} in formato Landscape</p>
    <p class="card-text">Copie vendute: {{ f.acquisto_count }} !</p>
    <br>
    <br> comprala per soli {{ f.price }}
{% else %}
    <p class="card-text">foto scattata da {{ f.artist.username }} in formato Portrait</p>
    <p class="card-text">Copie vendute: {{ f.acquisto_count }}!</p>
    <br>
    <br> a partire da: {{ f.price }}
{% endif %}


        </div>
        <div class="card-footer">
            <a href="{% url 'APPfoto:acquisto' f.pk %}" class="btn btn-info">
                Procedi alla composizione della foto </a>
        </div>
    </div>
    <br>
    {% endfor %}


{% else %}
    <p>No photos available.</p>
    <!-- Redirect dopo 3 secondi -->
    <meta http-equiv="refresh" content="3;url={% url 'APPfoto:cercaFoto' %}">
{% endif %}
<br>

{% endblock %}

APPfoto/templates/APPfotoTempl/lista_fotografi.html
{% extends 'base.html' %}

{% block title %}Elenco Fotografi{% endblock %}

{% load static %}

{% block header1 %}
  <h1>Elenco Fotografi</h1>
{% endblock %}

{% block content %}
<h2>Elenco di tutti i Fotografi</h2>
    <br>
    <h3> Ordina per: </h3>

<div class="btn-group" role="group">
    <a href="?sort=positive_reviews" class="btn btn-secondary">Recensioni Migliori</a>
    <a href="?sort=alphabetical" class="btn btn-secondary">Alfabetico</a>
    <a href="?sort=best_seller" class="btn btn-secondary">Best Seller</a>
</div>
<br>
<br>
<br>
<br>

{% if members %}
    {% for member in members %}
    <div class="card mb-3">
        <div class="card-body">
            <a href="{% url 'APPfoto:ricerca_risultati' member.id 'artist' %}">
                    {{ member.username }}
                </a>
                <p class="card-text"> Ha creato : {{ member.foto_count }} fotografie</p>
                <p class="card-text"> Valutazione degli Utenti: {{ member.average_review }}</p>
                <p class="card-text"> Foto vendute: {{ member.venduti_count }} </p>
        </div>
    </div>
    {% endfor %}
{% else %}
    <p>Non ci sono fotografi registrati... Strano, molto strano</p>
{% endif %}
<br>

{% endblock %}

APPfoto/templates/APPfotoTempl/recap_acquisto.html
{% extends 'base.html' %}

{% block title %} Acquisto Confirmation {% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %}
  <h1> Acquisto Confirmation </h1>
{% endblock %}

{% block content %}

<br>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">

      <p><strong>Acquirente:</strong> {{ acquisto.acquirente }}</p>
      <p><strong>Foto:</strong> {{ acquisto.foto }}</p>
      <p><strong>Prezzo di Partenza foto:</strong> {{ acquisto.foto.price }}</p>
      <p><strong>Materiale:</strong> {{ acquisto.get_materiale_display }}</p>
      <p><strong>Dimensioni:</strong> {{ acquisto.get_dimensioni_display }}</p>
      <p><strong>Per un totale di:</strong> {{ acquisto.prezzo }}</p>


      <!-- Conferma acquisto -->
    <form method="post" action="{% url 'APPfoto:situation' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Conferma Acquisto</button>
    </form>

    </div>
  </div>
</div>

<br>

{% endblock %}

APPfoto/templates/APPfotoTempl/recensione.html
{% extends 'base.html' %}

{% block title %} {{ view.title }} {% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %}
  <h1> Recensisci i tuoi acquisti </h1>
{% endblock %}

{% block content %}

    {% if user_has_recensione %}
<div class="alert alert-warning">
  Hai già recensito questa foto! <br>
  La recensione corrente non verrà salvata e dopo aver "confermato" verrai reindirizzato alla home
</div>
{% endif %}

<br>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Conferma la tua Recensione</button>
      </form>
    </div>
  </div>
</div>

<br>

{% endblock %}

APPfoto/templates/APPfotoTempl/recensioni_utente.html
{% extends 'base.html' %}

{% block title %} Recensioni di {{ user.username }} {% endblock %}

{% block header1 %}
  <h1>Recensioni di {{ user.username }} </h1>
  <p>Vediamo cosa ti è piaciuto
    {% if user.is_authenticated %}
     {{ user.username }}
    {% else %}
    Utente non registrato
    {% endif %}
  </p>
{% endblock %}

{% block content %}

     <br> <a href="{% url 'APPfoto:situation' %}" class="btn btn-info">Cronologia Acquisti</a>
    <br>
    <br>
    <br>
  <h2>Recensioni di {{ user.username }}</h2>
  {% for recensione in recensioni_utente %}
    <div class="card mb-4">
      <div class="card-body">
        <!-- INTERNPO DELLA CARD -->
        <h5 class="card-title">{{ recensione.foto.name }} di : {{ recensione.fotografo }}</h5>
        <p class="card-text">{{ recensione.testo_della_recensione }}</p>
        <p class="card-text"> Voto dato all'acquisto: {{ recensione.voto }}</p>

        <!-- AGGIUNGI ROBA QUI EVENTUALMENTE -->
      </div>
    </div>
  {% endfor %}
{% endblock %}

APPfoto/templates/APPfotoTempl/situation.html
{% extends 'base.html' %}

{% block title %} Home di {{ user.username }} {% endblock %}

{% block header1 %}
  <h1>Cronologia di {{ user.username }} </h1>
  <p>Benvenuto
    {% if user.is_authenticated %}
     {{ user.username }}
    {% else %}
    Utente non registrato
        <br>
        effettua il login per continuare
    {% endif %}
  </p>
{% endblock %}

{% block content %}
     <br> <a href="{% url 'APPfoto:RecensioniUtente' %}" class="btn btn-info">Visualizza Recensioni</a>
    <br>
    <br>
  <h2> Ecco l'elenco dei tuoi acquisti </h2>

  <br>


  {% for acquisto in user.acquisti.all reversed %}
    <div class="card">
      <div class="card-header">
                <img src="{{ acquisto.foto.actual_photo.url }}" alt="{{ f.name }}" style="max-width: 400px; max-height: 400px;">
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ acquisto.foto.name }}</h5>
        <p class="card-text">Una foto di {{ acquisto.foto.artist.username }} </p>
        <p class="card-text">Materiale: {{ acquisto.get_materiale_display }}</p>
        <p class="card-text">Dimensioni: {{ acquisto.get_dimensioni_display }}</p>
        <p class="card-text">Spesa totale: {{ acquisto.prezzo }}</p>

        <a href="{% url 'APPfoto:CreaRecensione' acquisto.pk %}" class="btn btn-info"> Scrivi una Recensione </a>


      </div>
    </div>
    <br>
  {% endfor %}

  <br>

{% endblock %}